name: Build ISO
on: [push]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash -c "
            ls -lah \
            chmod +x bin/omarchy-iso-make && \
            ./bin/omarchy-iso-make \
            ls -lah"
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: omarchy-iso-${{ github.run_number }}
          path: out/*.iso
          retention-days: 30
