name: Build ISO
on: [push]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x bin/omarchy-iso-make
      - name: Run the script
        run: ./bin/omarchy-iso-make --no-boot-offer
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: omarchy-iso-${{ github.run_number }}
          path: release/*.iso
          retention-days: 30
      - name: Create Tag
        id: create_tag
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: release/*.iso
          name: ${{ github.event.repository.updated_at}}-${{ github.run_number }}
          body: ${{ github.event.repository.updated_at}}
          make_latest: true
