name: Build ISO
on: [push]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x bin/omarchy-iso-make
      - name: Run the script
        run: ./bin/omarchy-iso-make && ls -lah
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: omarchy-iso-${{ github.run_number }}
          path: out/*.iso
          retention-days: 30
