name: Build ISO
on: [push]
jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Make the script files executable
        run: chmod +x bin/omarchy-iso-make
      - name: Run the script
        run: ./bin/omarchy-iso-make --no-boot-offer && for f in release/*.iso; do mv release/"$f" release/"${f%.iso}_${{ github.run_number }}.iso"; done
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: omarchy-iso-${{ github.run_number }}
          path: release/*.iso
          retention-days: 30
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          files: release/*.iso
          tag_name: main
