name: Nightly ISO Build

on:
  schedule:
    - cron: '1 0 * * *'  # Daily at 00:01 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-iso:
    runs-on: ubuntu-latest

    container:
      image: archlinux/archlinux:latest
      options: --rm --privileged -v "${{ github.workspace }}:/workspace" -w /workspace
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build ISO in Arch Linux container
      run: |
          bash -c "
            pacman -Syu --noconfirm && \
            chmod +x build_iso.sh && \
            ./build_iso.sh
          "
    
    - name: Upload ISO artifact
      uses: actions/upload-artifact@v4
      with:
        name: omarchy-iso-${{ github.run_number }}
        path: out/*.iso
        retention-days: 30
